export { default as Banner } from "./homepage-sections/Banner";
export { default as Pen } from "./homepage-sections/Pen";
export { default as Textboxes } from "./homepage-sections/Textboxes";
export { default as Products } from "./homepage-sections/Products";
export { default as Contact } from "./homepage-sections/Contact";
export { default as AboutBanner } from "./about-sections/About-banner";
export { default as AboutStoke } from "./about-sections/about-timeline";
export { default as Choices } from "./portfolio-sections/Choices";
export { default as CheckoutContainer } from "./checkout-sections/checkout-container";
